FROM python:3.11
MAINTAINER Damien Ayers <damien.ayers@ga.gov.au>

RUN apt-get update && apt-get install -y git pandoc

ADD requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt --no-cache


EXPOSE 8000
WORKDIR /tmp/docs
CMD /usr/local/bin/sphinx-autobuild --host 0.0.0.0 --port 8000 --ignore _build/ --ignore .git --ignore .idea -b html -j auto . _build/html
