FROM python:3.10-alpine
MAINTAINER Damien Ayers <damien.ayers@ga.gov.au>

# Install git so we can pull packages from git
# Will require changing to alpine instead of slim
RUN apk add --no-cache git pandoc

ADD requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt && pip install Sphinx==5.1.1 sphinx-autobuild==2021.3.14


EXPOSE 8000
WORKDIR /tmp/docs
CMD /usr/local/bin/sphinx-autobuild --host 0.0.0.0 --port 8000 --ignore _build/ --ignore .git --ignore .idea -b html -j auto . _build/html
